[server]
headless = true
port = 8501
address = "0.0.0.0"
# If you deploy behind a proxy and hit websocket/CORS issues:
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
